### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by tamirboker** [brenborbs/Waves-Ecommerce-Site#1]
Hello.
I tried to download your project but couldn't make it run. I tried starting it by using 'npm install' on the main folder and on the client folder and 'npm start' first on the server and then on the client but couldn't make it work. (All on Windows 10)
Could you send instructions on how to run the site?
In addition, I was wondering if there is any way we could talk more in private? I saw some of your work and would love to ask you some more questions and talk (I'm currently a student and could really use your help...).
Thank you very much!

**Comment by brenborbs** [comment]
Hi there,
I am sorry for the long delay of reply. I was very busy most of the time and I just noticed this message today. For some unknown reasons, Github just sent me the notification this afternoon.
To run the project:
1. First make sure your mongoDB is running. If you are using it locally, then make sure to start it.
Create an .env file and change the following details to your own.
MONGODB_URI=mongodb://localhost:27017/<yourprojectnamehere>
SECRET=YOURSECRETPASSWORD
CLOUD_NAME=name from your cloudinary account
CLOUD_API_KEY=api key from your cloudinary account
CLOUD_API_SECRET=api key secret from your cloudinary account
EMAIL_PASS=you can supply own email

2. To start the app, on package.json file, you can see under scripts, 
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server/server.js",
    "server": "nodemon server/server.js",
    "client": "npm run start --prefix client",
    "dev": "concurrently \"npm run server\" \"npm run client\"",
    "heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"
  },
On your main project directory, 
type "npm run dev" on terminal
This command will run both front-end and server-side by using concurrently package.

I am sorry, I am using macbook pro settings and I am not so familiar with the windows10 environment. But you can find many tutorials on the internet. 
If you have some problems, my email is borbonbrennon@gmail.com.
I will try to answer your questions as possibly as I can. 
Good luck!
